stages:
  prepare:
    cmd: python src/job_post_nlp/prepare.py
    deps:
    - data/Jobnet.xlsx
    - src/job_post_nlp/prepare.py
    params:
    - prepare
    outs:
    - data/corpus.spacy
  train:
    cmd: python src/job_post_nlp/train.py
    deps:
    - data/corpus.spacy
    - src/job_post_nlp/train.py
    params:
    - train
    outs:
    - data/most_common_words.json
  evaluate:
    cmd: python src/job_post_nlp/evaluate.py
    deps:
    - data/most_common_words.json
    - src/job_post_nlp/evaluate.py
plots:
- output/plots/images
- output/plots/custom/Most Common Words.json:
    template: bar_horizontal
    x: Frequency
    y: Word
    title: Most Common Words Bar Plot
metrics:
- output/metrics.json
