stages:
  prepare:
    cmd: python .\src\job_post_nlp\prepare.py
    deps:
    - .\data\Jobnet.xlsx
    - .\src\job_post_nlp\prepare.py
    params:
    - prepare.nobs
    outs:
    - .\data\tokenized_texts.json
  train:
    cmd: python .\src\job_post_nlp\train.py
    deps:
    - .\data\tokenized_texts.json
    - .\src\job_post_nlp\train.py
    params:
    - train.top_n
    outs:
    - .\data\most_common_words.json
  evaluate:
    cmd: python src\job_post_nlp\evaluate.py
    deps:
    - .\data\most_common_words.json
    - .\src\job_post_nlp\evaluate.py
plots:
- dvclive/plots/images
- dvclive/plots/custom/Most Common Words.json:
    template: bar_horizontal
    x: Frequency
    y: Word
    title: Most Common Words Bar Plot
- output/plots/images
- output/plots/custom/Most Common Words.json:
    template: bar_horizontal
    x: Frequency
    y: Word
    title: Most Common Words Bar Plot
metrics:
- dvclive/metrics.json
- output/metrics.json
