stages:
  prepare:
    cmd: python src/job_post_nlp/prepare.py
    deps:
    - data/Jobnet.xlsx
    - src/job_post_nlp/prepare.py
    params:
    - prepare
    outs:
    - data/corpus.spacy
    - data/tdm.parquet
  train:
    cmd: python src/job_post_nlp/train.py
    deps:
    - data/tdm.parquet
    - src/job_post_nlp/train.py
    params:
    - train
    outs:
    - models/corex_model.pkl
  evaluate:
    cmd: python src/job_post_nlp/evaluate.py
    deps:
    - models/corex_model.pkl
    - src/job_post_nlp/evaluate.py

metrics:
- output/metrics.json
plots:
- output/plots/images
- output/plots/custom/Total Correlation.json:
    template: bar_horizontal_sorted
    x: TC
    y: Topic
    title: Total Correlation of Topics
- output/plots/custom/Number of Job Posts per Topic.json:
    template: bar_horizontal_sorted
    x: Number of Job Posts
    y: Topic
    title: Number of Job Posts per Topic
