prepare:
  settings:
    nobs: 1000
    batch_size: 50
    threads: 4
  preprocessing:
    model: da_core_news_sm
    pipeline:
    - tok2vec
    - lemmatizer
    keep_negations: true
  tdm:
    tdm_cell: binary
    ngram_n: 2
    min_df:
    - 1
    - 0.01
    - 0.01
    - 0.01
    - 0.01
train:
  settings:
    verbose: false
    max_iter: 200
    seed: 17
  corex:
    n_topics: 50
    anchors: null
    anchor_strength: null
